{ pkgs, ... }: {
  programs.nix-ld.enable = true;
  programs.nix-ld.libraries = with pkgs; [
    gtk3
    gtk2
    glib
    gdk-pixbuf
    cairo
    pango
    atk
    freetype
    fontconfig
    dbus
    nspr
    nss
    libnotify
    xorg.libX11
    xorg.libXcomposite
    xorg.libXcursor
    xorg.libXdamage
    xorg.libXext
    xorg.libXfixes
    xorg.libXi
    xorg.libXrandr
    xorg.libXrender
    xorg.libXtst
    xorg.libxcb
    xorg.xcbutilimage
    xorg.xcbutilkeysyms
    xorg.xcbutilrenderutil
    xorg.xcbutilwm
    at-spi2-atk
    at-spi2-core
    libdrm
    mesa
    xorg.libxshmfence
    alsa-lib
    cups
    expat
    zlib
    stdenv.cc.cc.lib
  ];
}